version: 2
jobs:
  deploy-develop:
    docker:
      -
        image: 'buildpack-deps:trusty'
    environment:
      DEPLOY_SCRIPT: ./deploy.sh
      REMOTE_HOST: mmc.dev.coretec.io
      REMOTE_USER: ubuntu
    steps:
      -
        run:
          name: 'Deploy over SSH to development server'
          command: 'ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "$DEPLOY_SCRIPT"'
workflows:
  version: 2
  deploy-develop:
    jobs:
      -
        deploy-develop:
          filters:
            branches:
              only: develop
          context: develop
